name: Main CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip

      - name: Check formatting with black
        run: |
          pip install black
          black --check splicer/cli.py

      - name: Run Mypy
        run: |
          pip install mypy
          mypy splicer/cli.py
